name: Java CI with Maven

on: [push, pull_request]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Unit Test with Maven
        run: mvn -B clean test --file pom.xml

  sonarcloud:
    name: sonarcloud
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  registry:
    runs-on: ubuntu-latest
    needs: [test, sonarcloud]
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: |
          docker login -u imedznd -p ${{secrets.DOCKER_PASS}}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag imedznd/history-service:latest
      - name: Docker Push
        run: docker push imedznd/history-service

